SELECT 'Upgrading MetaStore schema from 2.1.0 to 2.2.0' AS MESSAGE;

ALTER TABLE TBLS ADD IS_REWRITE_ENABLED bit NOT NULL DEFAULT 0;
ALTER TABLE NOTIFICATION_LOG ADD MESSAGE_FORMAT nvarchar(16);
ALTER TABLE "SERDE_PARAMS" ALTER COLUMN "PARAM_VALUE" VARCHAR(MAX);
ALTER TABLE "TABLE_PARAMS" ALTER COLUMN "PARAM_VALUE" VARCHAR(MAX);
ALTER TABLE "SD_PARAMS" ALTER COLUMN "PARAM_VALUE" VARCHAR(MAX);
-- FIXED
alter table COLUMNS_V2 drop CONSTRAINT COLUMNS_PK ;
---
ALTER TABLE "COLUMNS_V2" ALTER COLUMN "TYPE_NAME" VARCHAR(MAX);
-- FIXED
ALTER TABLE "COLUMNS_V2" ADD CONSTRAINT COLUMNS_PK PRIMARY KEY (CD_ID,COLUMN_NAME);
--- 


ALTER TABLE "TBLS" ALTER COLUMN "TBL_NAME" nvarchar(256);
ALTER TABLE "NOTIFICATION_LOG" ALTER COLUMN "TBL_NAME" nvarchar(256);
ALTER TABLE "PARTITION_EVENTS" ALTER COLUMN "TBL_NAME" nvarchar(256);
ALTER TABLE "TAB_COL_STATS" ALTER COLUMN "TABLE_NAME" nvarchar(256);
ALTER TABLE "PART_COL_STATS" ALTER COLUMN "TABLE_NAME" nvarchar(256);
ALTER TABLE "COMPLETED_TXN_COMPONENTS" ALTER COLUMN "CTC_TABLE" varchar(256);

-- FIXED
alter table COLUMNS_V2 drop CONSTRAINT COLUMNS_PK ;
---
ALTER TABLE "COLUMNS_V2" ALTER COLUMN "COLUMN_NAME" nvarchar(767) NOT NULL;
-- FIXED
ALTER TABLE "COLUMNS_V2" ADD CONSTRAINT COLUMNS_PK PRIMARY KEY (CD_ID,COLUMN_NAME);
---
--- ALTER TABLE "PART_COL_PRIVS" ALTER COLUMN "COLUMN_NAME" nvarchar(767) DEFAULT NULL;
--FIXED
drop index PARTITIONCOLUMNPRIVILEGEINDEX on PART_COL_PRIVS
ALTER TABLE "PART_COL_PRIVS" ALTER COLUMN "COLUMN_NAME" nvarchar(767) NULL;
CREATE NONCLUSTERED INDEX PARTITIONCOLUMNPRIVILEGEINDEX ON PART_COL_PRIVS (  PART_ID ASC  , COLUMN_NAME ASC  , PRINCIPAL_NAME ASC  , PRINCIPAL_TYPE ASC  , PART_COL_PRIV ASC  , GRANTOR ASC  , GRANTOR_TYPE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
---

---ALTER TABLE "TBL_COL_PRIVS" ALTER COLUMN "COLUMN_NAME" nvarchar(767) DEFAULT NULL;
-- FIXED
DROP INDEX TABLECOLUMNPRIVILEGEINDEX ON TBL_COL_PRIVS;
ALTER TABLE "TBL_COL_PRIVS" ALTER COLUMN "COLUMN_NAME" nvarchar(767)  NULL;
CREATE NONCLUSTERED INDEX TABLECOLUMNPRIVILEGEINDEX ON TBL_COL_PRIVS (  TBL_ID ASC  , COLUMN_NAME ASC  , PRINCIPAL_NAME ASC  , PRINCIPAL_TYPE ASC  , TBL_COL_PRIV ASC  , GRANTOR ASC  , GRANTOR_TYPE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;

---ALTER TABLE "SORT_COLS" ALTER COLUMN "COLUMN_NAME" nvarchar(767) DEFAULT NULL;
ALTER TABLE "SORT_COLS" ALTER COLUMN "COLUMN_NAME" nvarchar(767)  NULL;

ALTER TABLE "TAB_COL_STATS" ALTER COLUMN "COLUMN_NAME" nvarchar(767) NOT NULL;

-- FIXED
DROP INDEX PCS_STATS_IDX ON PART_COL_STATS;
ALTER TABLE "PART_COL_STATS" ALTER COLUMN "COLUMN_NAME" nvarchar(767) NOT NULL;
CREATE NONCLUSTERED INDEX PCS_STATS_IDX ON PART_COL_STATS (  DB_NAME ASC  , TABLE_NAME ASC  , COLUMN_NAME ASC  , PARTITION_NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
--


UPDATE VERSION SET SCHEMA_VERSION='2.2.0', VERSION_COMMENT='Hive release version 2.2.0' where VER_ID=1;
SELECT 'Finished upgrading MetaStore schema from 2.1.0 to 2.2.0' AS MESSAGE;
