SELECT 'Upgrading MetaStore schema from 1.2.0 to 2.0.0' AS MESSAGE;
-- FIXED
alter table COLUMNS_V2 drop CONSTRAINT COLUMNS_PK ;
---
ALTER TABLE "COLUMNS_V2" ALTER COLUMN "COLUMN_NAME" VARCHAR(1000) NOT NULL;
-- FIXED
ALTER TABLE "COLUMNS_V2" ADD CONSTRAINT COLUMNS_PK PRIMARY KEY (CD_ID,COLUMN_NAME)
---
-- FIXED
drop index PARTITIONCOLUMNPRIVILEGEINDEX on PART_COL_PRIVS;
---
ALTER TABLE "PART_COL_PRIVS" ALTER COLUMN "COLUMN_NAME" VARCHAR(1000) NULL;
-- FIXED
CREATE NONCLUSTERED INDEX PARTITIONCOLUMNPRIVILEGEINDEX ON PART_COL_PRIVS (  PART_ID ASC  , COLUMN_NAME ASC  , PRINCIPAL_NAME ASC  , PRINCIPAL_TYPE ASC  , PART_COL_PRIV ASC  , GRANTOR ASC  , GRANTOR_TYPE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
---
-- FIXED
DROP INDEX TABLECOLUMNPRIVILEGEINDEX ON TBL_COL_PRIVS;
---
ALTER TABLE "TBL_COL_PRIVS" ALTER COLUMN "COLUMN_NAME" VARCHAR(1000) NULL;
-- FIXED
CREATE NONCLUSTERED INDEX TABLECOLUMNPRIVILEGEINDEX ON TBL_COL_PRIVS (  TBL_ID ASC  , COLUMN_NAME ASC  , PRINCIPAL_NAME ASC  , PRINCIPAL_TYPE ASC  , TBL_COL_PRIV ASC  , GRANTOR ASC  , GRANTOR_TYPE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
---



ALTER TABLE "SORT_COLS" ALTER COLUMN "COLUMN_NAME" VARCHAR(1000) NULL;
ALTER TABLE "TAB_COL_STATS" ALTER COLUMN "COLUMN_NAME" VARCHAR(1000) NOT NULL;

-- FIXED
DROP INDEX PCS_STATS_IDX ON PART_COL_STATS;
--

ALTER TABLE "PART_COL_STATS" ALTER COLUMN "COLUMN_NAME" VARCHAR(1000) NOT NULL;
-- FIXED
CREATE NONCLUSTERED INDEX PCS_STATS_IDX ON PART_COL_STATS (  DB_NAME ASC  , TABLE_NAME ASC  , COLUMN_NAME ASC  , PARTITION_NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
---

ALTER TABLE COMPACTION_QUEUE ADD CQ_HIGHEST_TXN_ID bigint NULL;
ALTER TABLE COMPACTION_QUEUE ADD CQ_META_INFO varbinary(2048) NULL;
ALTER TABLE COMPACTION_QUEUE ADD CQ_HADOOP_JOB_ID nvarchar(32) NULL;
CREATE TABLE COMPLETED_COMPACTIONS (
	CC_ID bigint NOT NULL,
	CC_DATABASE nvarchar(128) NOT NULL,
	CC_TABLE nvarchar(128) NOT NULL,
	CC_PARTITION nvarchar(767) NULL,
	CC_STATE char(1) NOT NULL,
	CC_TYPE char(1) NOT NULL,
	CC_WORKER_ID nvarchar(128) NULL,
	CC_START bigint NULL,
	CC_END bigint NULL,
	CC_RUN_AS nvarchar(128) NULL,
	CC_HIGHEST_TXN_ID bigint NULL,
    CC_META_INFO varbinary(2048) NULL,
	CC_HADOOP_JOB_ID nvarchar(128) NULL,
PRIMARY KEY CLUSTERED 
(
	CC_ID ASC
)
);


ALTER TABLE TXNS ADD TXN_AGENT_INFO nvarchar(128) NULL;
ALTER TABLE TXNS ADD TXN_HEARTBEAT_COUNT int NULL;
ALTER TABLE HIVE_LOCKS ADD HL_HEARTBEAT_COUNT int NULL;
ALTER TABLE TXNS ADD TXN_META_INFO nvarchar(128) NULL;
ALTER TABLE HIVE_LOCKS ADD HL_AGENT_INFO nvarchar(128) NULL;
ALTER TABLE HIVE_LOCKS ADD HL_BLOCKEDBY_EXT_ID bigint NULL;
ALTER TABLE HIVE_LOCKS ADD HL_BLOCKEDBY_INT_ID bigint NULL;
CREATE TABLE AUX_TABLE (
  MT_KEY1 nvarchar(128) NOT NULL,
  MT_KEY2 bigint NOT NULL,
  MT_COMMENT nvarchar(255) NULL,
  PRIMARY KEY CLUSTERED
(
    MT_KEY1 ASC,
    MT_KEY2 ASC
)
);

UPDATE VERSION SET SCHEMA_VERSION='2.0.0', VERSION_COMMENT='Hive release version 2.0.0' where VER_ID=1;
SELECT 'Finished upgrading MetaStore schema from 1.2.0 to 2.0.0' AS MESSAGE;
